=== mod-sig/eng517-fall2026/pacenotesDTD/pacenotes.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT stage-notes (start-note,note+,end-note)>
<!ELEMENT start-note (start,note)>
<!ELEMENT start (#PCDATA)>
<!ELEMENT note (turn-note|distance-note|warning-note)>
<!ELEMENT turn-note (modifier?,severity,direction,modifier*)>

<!-- a reason for "modifier" appearing twice? I believe that the "?" and the "*" both mean zero or more so you may not need both -->

<!ELEMENT modifier (#PCDATA)>
<!ELEMENT severity (#PCDATA)>
<!ELEMENT direction (#PCDATA)>
<!ELEMENT distance-note (distance,modifier?)>
<!ELEMENT distance (#PCDATA)>
<!ELEMENT warning-note (#PCDATA)>
<!ELEMENT end-note (finish,note+,stop)>
<!ELEMENT finish (#PCDATA)>
<!ELEMENT stop (#PCDATA)>

=== mod-sig/eng517-fall2026/pacenotesDTD/pacenotes.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="pacenotes.css"?>
<!DOCTYPE stage-notes SYSTEM "pacenotes.dtd">

<stage-notes>
    <start-note>
        <start>starts</start>
        <distance-note>
            <distance>200</distance>
            <modifier>onto gravel</modifier>
        </distance-note>
<!-- according to the DTD, there should also be a "note" element in here -->
        
    </start-note>
    <note><turn-note>
        <severity>5</severity>
        <direction>R</direction>
        <modifier>+</modifier>
        <modifier>long</modifier>
    </turn-note></note>
    <note><distance-note>
        <distance>70</distance>
    </distance-note></note>
    <note><warning-note>caution over crest</warning-note></note>
    <note><turn-note>
        <modifier>early</modifier>
        <severity>3</severity>
        <direction>L</direction>
    </turn-note></note>
    <note><turn-note>
        <severity>3</severity>
        <direction>R</direction>
    </turn-note></note>
    <note><turn-note>
        <severity>6</severity>
        <direction>L</direction>
        <modifier>extra long</modifier>
        <modifier>onto tarmac</modifier>
    </turn-note></note>
    <note><distance-note>
        <distance>200</distance>
        </distance-note></note>
    <end-note>
        <finish>over finish</finish>
        <turn-note>
            <severity>4</severity>
            <direction>R</direction>
        </turn-note>
        <stop>to stop</stop>
    </end-note>
</stage-notes>
